import { useEffect, useMemo, useState } from 'react'
import { api } from '../api/client'
import { ArtifactSummary } from '../types'

function DocsPage() {
  const [artifacts, setArtifacts] = useState<ArtifactSummary | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    api
      .get<ArtifactSummary>('/artifacts')
      .then((res) => setArtifacts(res.data))
      .catch(() => setArtifacts(null))
      .finally(() => setLoading(false))
  }, [])

  const docsUrl = useMemo(() => {
    if (!artifacts?.docs) return ''
    const base = (api.defaults.baseURL || '').replace(/\/$/, '')
    return `${base}/artifacts/docs/index.html`
  }, [artifacts?.docs])

  const refreshStatus = () => {
    setLoading(true)
    api
      .get<ArtifactSummary>('/artifacts')
      .then((res) => setArtifacts(res.data))
      .catch(() => setArtifacts(null))
      .finally(() => setLoading(false))
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold text-text">Docs</h1>
          <p className="text-muted text-sm">
            View the complete dbt documentation generated by <code className="text-xs font-mono text-text">dbt docs generate</code>.
          </p>
        </div>
        <button
          onClick={refreshStatus}
          className="px-3 py-1 text-sm rounded bg-surface border border-border text-text hover:border-accent"
          disabled={loading}
        >
          {loading ? 'Checking…' : 'Refresh'}
        </button>
      </div>

      {!artifacts?.docs && !loading && (
        <div className="bg-panel border border-border rounded-lg p-4 text-sm text-text space-y-2">
          <p className="font-semibold text-text">Docs not found</p>
          <p className="text-text">
            Generate documentation in your dbt project and make sure the resulting <code>target</code> directory is available
            in your configured artifacts path. Run <code>dbt docs generate</code> and rerun a sync to publish the full docs site
            here.
          </p>
          <p className="text-muted text-xs">
            We look for the <code>index.html</code> created by dbt inside the artifacts directory to render the complete site.
          </p>
        </div>
      )}

      {artifacts?.docs && (
        <div className="bg-panel border border-border rounded-lg overflow-hidden">
          <div className="flex items-center justify-between px-4 py-2 border-b border-border text-sm text-text">
            <span>dbt Docs Viewer</span>
            <a
              href={docsUrl}
              target="_blank"
              rel="noreferrer"
              className="text-accent hover:underline"
            >
              Open in new tab
            </a>
          </div>
          <iframe
            src={docsUrl}
            title="dbt Docs"
            className="w-full"
            style={{ minHeight: '70vh', backgroundColor: '#0b0b0f' }}
          />
        </div>
      )}

      {loading && (
        <div className="text-sm text-muted">Checking for generated documentation…</div>
      )}
    </div>
  )
}

export default DocsPage
